name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/simplycoders/hello-world-api-server:latest
    - name: Login to ghcr.io
      run: docker login ghcr.io --username ${{ secrets.USER }} --password ${{ secrets.PAT }}
    - name: Push to ghcr.io
      run: docker push ghcr.io/simplycoders/hello-world-api-server:latest
