name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }}
    - 
      name: Build the Docker image
      run: docker build -build-arg BASE_IMAGE=amd64/node:16 . --file Dockerfile --tag ghcr.io/simplycoders/hello-world-api-server:latest
    - 
      name: Push to ghcr.io
      run: docker push ghcr.io/simplycoders/hello-world-api-server:latest
    