name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ secrets.USER }}/hello-world-api
          tags: latest