name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: login
      uses: docker/login-action@v1
      with:
        registry: hub.docker.com
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag simplycoders/hello-world-api:latest
    - 
      name: Push
      run: docker push simplycoders/hello-world-api:latest
      